[ Work In Progress ] Landing Page Redesign
nairuby/arc_platform pull request #84
Opened 2024-04-16 08:35 UTC by Annastacia-dev

- work in progress

2024-04-18 21:55 UTC, JudahSan commented
Props for improving the design @Annastacia-dev 
Kindly fix the conflicting files

2024-04-19 07:17 UTC, Annastacia-dev commented
> Props for improving the design @Annastacia-dev Kindly fix the conflicting files

Hello, the PR is still a work in progress will fix and also let you know when it's ready for review, let's hold on that

2024-05-16 10:38 UTC, Annastacia-dev commented
@JudahSan the PR is ready

2024-05-16 14:04 UTC, JudahSan commented on app/views/layouts/_footer.html.erb
![image](https://github.com/nairuby/arc_platform/assets/61739631/d018463f-d2e5-4dab-b188-45e9c4299185)

Footer comparison between the old and new design.

2024-05-16 14:10 UTC, JudahSan commented on app/views/layouts/_navbar.html.erb
![image](https://github.com/nairuby/arc_platform/assets/61739631/1dc72c06-19bf-4311-8768-2a79531f26d5)

@Annastacia-dev  Missing closing navbar tag: `</navbar>`

2024-05-16 14:47 UTC, JudahSan requested changes

2024-05-16 14:47 UTC, JudahSan commented on app/views/layouts/_footer.html.erb
@Annastacia-dev The footer is great on big screens but lacks optimization for small screens.

2024-05-16 14:47 UTC, JudahSan commented on app/views/layouts/_navbar.html.erb
![image](https://github.com/nairuby/arc_platform/assets/61739631/1dc72c06-19bf-4311-8768-2a79531f26d5)

@Annastacia-dev  Missing closing navbar tag: `</navbar>`

2024-05-16 14:51 UTC, JudahSan commented
> @JudahSan the PR is ready for review

Reviewed. Nice work.

2024-05-16 16:22 UTC, denissellu commented
@Annastacia-dev this is great work! thanks!

I love that you are bring in annotate! 👏

how would you feel to cherry-pick it in to another PR? this commit? https://github.com/nairuby/arc_platform/pull/84/commits/63a113f311d1f495e3ec8dcd2e83a952af9445f2
it'll help make review easier and keep this PR focused on the style changes

2024-05-16 16:24 UTC, Annastacia-dev commented on app/views/layouts/_navbar.html.erb
noted, will fix

2024-05-16 16:32 UTC, denissellu requested changes
@Annastacia-dev thanks for the work on here!

just small changes to move the arrays create in the partials into helpers, so the templates can be tidier and easier to manage. 

what do you think?

2024-05-16 16:32 UTC, denissellu commented on app/views/landing/home/_activities.html.erb
> +
please move this in to a helper

2024-05-16 16:32 UTC, denissellu commented on app/views/landing/home/_chapters.html.erb
> +] %>
move this too in to a helper 🙏

2024-05-16 16:32 UTC, denissellu commented on app/views/landing/home/_featured_sponsors.html.erb
> +] %>
in to a helper too please

2024-05-16 16:32 UTC, denissellu commented on app/views/landing/home/_previous_sponsors.html.erb
> +] %>
into a helper 🙏

2024-05-16 16:32 UTC, denissellu commented on app/views/layouts/_footer.html.erb
> +] %>
into a helper 🙏

2024-05-19 01:23 UTC, JudahSan approved these changes

2024-05-20 14:58 UTC, denissellu approved these changes
👏 nice one!

2024-05-20 15:53 UTC, merged